apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: aplicatie
        image: europe-west3-docker.pkg.dev/ino-ols-newops-sbx/proiectradu2/nginx:1.0
        ports:
        - containerPort: 80
